//@ui5-bundle io/pragmatiqu/auth/Component-preload.js
sap.ui.predefine("io/pragmatiqu/auth/Component", ["sap/ui/core/UIComponent","./model/models","sap/ui/Device","com/laravelui5/core/LaravelUi5"],function(t,e,i,n){"use strict";function s(t){return t&&t.__esModule&&typeof t.default!=="undefined"?t.default:t}const o=s(e);const a=s(n);const c=t.extend("io.pragmatiqu.auth.Component",{metadata:{manifest:"json",interfaces:["sap.ui.core.IAsyncContentCreation"]},init:function e(){t.prototype.init.call(this);this.setModel(o.createDeviceModel(),"device");a.init(this).then(()=>{this.getRouter().initialize()}).catch(t=>{console.error(t)})},getContentDensityClass:function t(){if(this.contentDensityClass===undefined){if(document.body.classList.contains("sapUiSizeCozy")||document.body.classList.contains("sapUiSizeCompact")){this.contentDensityClass=""}else if(!i.support.touch){this.contentDensityClass="sapUiSizeCompact"}else{this.contentDensityClass="sapUiSizeCozy"}}return this.contentDensityClass}});return c});
sap.ui.predefine("io/pragmatiqu/auth/controller/App.controller", ["./BaseController"],function(t){"use strict";function e(t){return t&&t.__esModule&&typeof t.default!=="undefined"?t.default:t}const n=e(t);const o=n.extend("io.pragmatiqu.auth.controller.App",{onInit:function t(){this.getView().addStyleClass(this.getOwnerComponent().getContentDensityClass())}});return o});
sap.ui.predefine("io/pragmatiqu/auth/controller/BaseController", ["sap/ui/core/mvc/Controller","sap/ui/core/UIComponent","sap/ui/core/routing/History"],function(e,t,n){"use strict";const o=e.extend("io.pragmatiqu.auth.controller.BaseController",{getOwnerComponent:function t(){return e.prototype.getOwnerComponent.call(this)},getRouter:function e(){return t.getRouterFor(this)},getResourceBundle:function e(){const t=this.getOwnerComponent().getModel("i18n");return t.getResourceBundle()},getModel:function e(t){return this.getView().getModel(t)},setModel:function e(t,n){this.getView().setModel(t,n);return this},navTo:function e(t,n,o){this.getRouter().navTo(t,n,undefined,o)},onNavBack:function e(){const t=n.getInstance().getPreviousHash();if(t!==undefined){window.history.go(-1)}else{this.getRouter().navTo("main",{},undefined,true)}}});return o});
sap.ui.predefine("io/pragmatiqu/auth/controller/Login.controller", ["./BaseController","sap/ui/model/json/JSONModel","sap/m/MessageBox"],function(n,e,t){"use strict";function o(n){return n&&n.__esModule&&typeof n.default!=="undefined"?n.default:n}const s=o(n);const i=s.extend("io.pragmatiqu.auth.controller.Login",{onInit:function n(){const t=this.getOwnerComponent();const o=t.getManifestEntry("/laravel.ui5/meta");const s=new e({email:null,password:null,meta:o});this.setModel(s,"login")},onLogin:async function n(){t.error("So isses!")}});return i});
sap.ui.predefine("io/pragmatiqu/auth/model/formatter", [],function(){"use strict";var e={formatValue:e=>e?.toUpperCase()};return e});
sap.ui.predefine("io/pragmatiqu/auth/model/models", ["sap/ui/model/json/JSONModel","sap/ui/model/BindingMode","sap/ui/Device"],function(e,i,n){"use strict";var d={createDeviceModel:()=>{const d=new e(n);d.setDefaultBindingMode(i.OneWay);return d}};return d});
sap.ui.require.preload({
	"io/pragmatiqu/auth/i18n/i18n.properties":'appTitle=io.pragmatiqu.auth\nappDescription=UI5 Application io.pragmatiqu.auth\nbtnText=Say Hello\n',
	"io/pragmatiqu/auth/i18n/i18n_de.properties":'appTitle=io.pragmatiqu.auth\nappDescription=UI5 Application io.pragmatiqu.auth\nbtnText=Sag Hallo\n',
	"io/pragmatiqu/auth/i18n/i18n_en.properties":'appTitle=io.pragmatiqu.auth\nappDescription=UI5 Application io.pragmatiqu.auth\nbtnText=Say Hello\n',
	"io/pragmatiqu/auth/manifest.json":'{"_version":"1.60.0","sap.app":{"id":"io.pragmatiqu.auth","type":"application","i18n":{"bundleUrl":"i18n/i18n.properties","supportedLocales":["","de","en"]},"title":"{{appTitle}}","description":"{{appDescription}}","applicationVersion":{"version":"1.0.0"},"sourceTemplate":{"id":"generator-ui5-ts-app","version":"1.1.0"}},"sap.ui":{"technology":"UI5","icons":{},"deviceTypes":{"desktop":true,"tablet":true,"phone":true}},"sap.ui5":{"rootView":{"viewName":"io.pragmatiqu.auth.view.App","type":"XML","id":"app"},"dependencies":{"minUI5Version":"1.136.8","libs":{"sap.ui.core":{},"sap.m":{},"sap.f":{},"com.laravelui5.core":{}}},"handleValidation":true,"contentDensities":{"compact":true,"cozy":true},"models":{"i18n":{"type":"sap.ui.model.resource.ResourceModel","settings":{"bundleName":"io.pragmatiqu.auth.i18n.i18n","supportedLocales":["en","de"],"fallbackLocale":"en","async":true}}},"routing":{"config":{"routerClass":"sap.m.routing.Router","type":"View","viewType":"XML","path":"io.pragmatiqu.auth.view","controlId":"app","controlAggregation":"pages"},"routes":[{"pattern":"","name":"login","target":"login"}],"targets":{"login":{"id":"login","name":"Login"}}},"flexBundle":false},"laravel.ui5":{"meta":{"terms":"/terms","privacy":"/privacy","cookies":"/cookies"}}}',
	"io/pragmatiqu/auth/view/App.view.xml":'<mvc:View\n\tcontrollerName="io.pragmatiqu.auth.controller.App"\n\tdisplayBlock="true"\n\txmlns="sap.m"\n\txmlns:mvc="sap.ui.core.mvc"\n><App id="app" /></mvc:View>\n',
	"io/pragmatiqu/auth/view/Login.view.xml":'<mvc:View\n    controllerName="io.pragmatiqu.auth.controller.Login"\n    displayBlock="true"\n    xmlns="sap.m"\n    xmlns:core="sap.ui.core"\n    xmlns:mvc="sap.ui.core.mvc"\n    xmlns:f="sap.f"\n><FlexBox\n        height="100%"\n        direction="Column"\n        alignItems="Center"\n        justifyContent="Center"><f:Card width="25em"\n                height="60vh"><f:layoutData><f:GridContainerItemLayoutData columns="4"/></f:layoutData><f:content><Page class="bg-white"><customHeader><Toolbar><Title text="Sign In" level="H1" class="sapUiTinyMarginBegin"/></Toolbar></customHeader><VBox\n                        width="90%"\n                        class="sapUiMediumMarginTop sapUiSmallMargin"\n                    ><Label text="Email, User ID or Login Name" class="sapUiNoMargin"/><Input\n                            id="emailInput"\n                            width="100%"\n                            value="{login>/email}"\n                            placeholder="Enter E-Mail"/><HBox justifyContent="End" width="100%"><Link\n                                text="Change"\n                                href="#/Forgot"\n                            /></HBox><Label text="Password" class="sapUiNoMargin"/><Input\n                            class="sapUiNoPadding"\n                            id="passwordInput"\n                            width="100%"\n                            value="{login>/password}"\n                            type="Password"\n                            placeholder="Enter password"/><HBox justifyContent="SpaceBetween" width="100%"><CheckBox\n                                text="Keep me signed in"\n                                selected="false"\n                                name="keepSignedIn"\n                                class="sapUiNoContentPadding"/><Link\n                                text="Forgot Password"\n                                href="#/Forgot"\n                                press="onNavigate"\n                                class="sapUiSmallMarginTop"><customData><core:CustomData key="pattern" value="Forgot" /></customData></Link></HBox></VBox><footer><Toolbar><ToolbarSpacer/><Button text="Continue" type="Emphasized" width="auto" press=".onLogin" /></Toolbar></footer></Page></f:content></f:Card><HBox\n            justifyContent="Center"\n            alignItems="Center"\n            width="100%"\n            class="sapUiSmallMarginTop sapUiSmallMarginBottom"\n        ><Link text="Privacy Policy" href="{login>/meta/privacy}" target="_blank" /><Text text="  |  " class="sapUiTinyMarginBegin sapUiTinyMarginEnd" /><Link text="Legal Disclosure" href="{login>/meta/terms}" target="_blank" /><Text text="  |  " class="sapUiTinyMarginBegin sapUiTinyMarginEnd" /><Link text="Cookie Statement" href="{login>/meta/cookies}" target="_blank" /></HBox></FlexBox></mvc:View>\n'
});
//# sourceMappingURL=Component-preload.js.map
