<?php

namespace LaravelUi5\Auth;

use LaravelUi5\Core\Ui5\AbstractUi5App;

/**
 * Framework-owned base for AuthApp.
 *
 * GENERATED by `ui5:app` and rewritten on every `ui5:app --refresh` — do NOT edit
 * by hand. Put your code in AuthApp (the leaf); it is never regenerated. The
 * members here are derived from the UI5 source build and re-sync on refresh: the
 * title/description and the bootstrap attributes / head script / CSS that change
 * when you add a `sap.*` library or adjust the UI5 project.
 */
abstract class AuthAppBase extends AbstractUi5App
{
    public const string TITLE = 'Login';
    public const string DESCRIPTION = 'Email and password sign-in for LaravelUi5 apps, with self-service password reset.';

    public function getUi5BootstrapAttributes(): array
    {
        return array (
  'on-init' => 'module:sap/ui/core/ComponentSupport',
  'compat-version' => 'edge',
  'frame-options' => 'trusted',
  'async' => 'true',
);
    }

    public function getAdditionalHeadScript(): ?string
    {
        return <<<JS

JS;
    }

    public function getAdditionalInlineCss(): ?string
    {
        return <<<CSS

CSS;
    }
}
